[package]
name = "mclib-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mclib-macros = { workspace = true }

flate2 = { workspace = true }
uuid = { workspace = true }
